# Generated by Django 3.0.5 on 2020-06-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200626_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
